name: Benchmark
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0'
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: package.json
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: benchmarks/pnpm-lock.yaml
      - working-directory: ./benchmarks
        run: pnpm install
      - working-directory: ./benchmarks
        env:
          PLOTLY_USERNAME: ${{ secrets.PLOTLY_USERNAME }}
          PLOTLY_APIKEY: ${{ secrets.PLOTLY_APIKEY }}
        run: pnpm run benchmark
